#!/bin/bash

outfolder="../output" # Folder used for results

file=$(basename -s .md $1) # Base name for file
outfile=${outfolder}/${file}
sols=${outfile}_solucions

# Make exercise by removing blocks between "begin hide" and "end hide"
sed '/begin hide/,/end hide/c"###### SOLUCIÓ AQUÍ ######"' ${file}.md | jupytext --to ipynb -o ${outfile}.ipynb

# Make solutions by removing lines containing "begin hide" and "end hide" markers
grep -v "begin hide" ${file}.md | grep -v "end hide" | jupytext --to ipynb -o ${sols}.ipynb

# Convert notebook (once executed, if possible) to LaTeX
(sage -jupyter nbconvert --to latex --execute --allow-errors ${outfile}.ipynb) || (sage -jupyter nbconvert --to latex --allow-errors ${outfile}.ipynb)

# Run pdflatex to obtain pdf
latexmk -output-directory=$outfolder -silent -pdf ${outfile}.tex
