# Workflow to publish all notebooks and upload to Nextcloud

name: Publish Notebooks

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Create a temporary artifact downloads folder
        run: mkdir -p exercises solutions html

      - name: Install dependencies
        run: sudo apt-get update && pip install jupytext
        
      - name: Add artifacts to publish to the temp folder
        run: for file in src/*md;
              do jupytext --to ipynb $file -o solutions/`basename -s .md $file`_solutions.ipynb;
              ./make-student-version solutions/`basename -s .md $file`_solutions.ipynb > exercises/`basename -s .md $file`.ipynb;
              done;
              
      - name: Upload exercises to Nextcloud
        run: for file in exercises/*.ipynb;
              do curl -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/exercicis/;
              done;
              
      - name: Upload solutions to Nextcloud
        run: for file in solutions/*.ipynb;
              do curl -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/solucions/;
              done;

      - name: Upload extra materials to Nextcloud
        run: for file in solutions/*.ipynb;
              do curl -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/exercicis/;
              done;
