# Workflow to publish all notebooks and upload to Nextcloud

name: Publish Notebooks

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image : sagemath/sagemath:latest
      options: --user root

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
        
      - name: Create a temporary artifact downloads folder
        run: mkdir -p output
            
      - name: Install more dependencies
        run: |
          sudo sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
          sudo apt-get update && sudo apt-get dist-upgrade
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git wget latexmk python3-pip curl texlive-latex-extra
          sudo pip install jupytext nbconvert ipython ipykernel
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo dpkg -i pandoc-2.18-1-amd64.deb
          sudo apt-get install -f

      - name: Make notebooks
        run: |
          cd src
          touch ../output/problems.txt
          for file in *.md; do
            if [ -f "$file" ]; then
              echo "Processing ${file}...";
              ../process_file $file || true;
            fi;
          done;
          cp problems.txt ../output
          cat ../output/*.log > ../output/all_logs.txt
          cd ..

      - name: Upload to Nextcloud
        run: for file in output/*.pdf output/*.ipynb output/all_logs.txt output/problems.txt; do
              if [ -f "$file" ]; then
                echo "Uploading ${file}...";
                curl --silent -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/exercicis/ || echo "Problem uploading ${file}";
              fi;
             done;

      - name: Upload extra files to Nextcloud
        run: for file in src/*.jpg src/*.png src/*.gif; do
              if [ -f "$file" ]; then
                echo "Uploading ${file}...";
                curl --silent -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/exercicis/ || echo "Problem uploading ${file}";
              fi;
             done;
