# Workflow to publish all notebooks and upload to Nextcloud

name: Publish Notebooks

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Create a temporary artifact downloads folder
        run: mkdir -p output

      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          sudo pip install jupytext
          sudo dpkg -i pandoc-2.18-1-amd64.deb
          sudo apt-get install -f
        
      - name: Make notebooks
        run: |
            cd src
            for file in *.md;
              do ../process_file $file
              done;
            cd ..
              
      - name: Upload to Nextcloud
        run: for file in output/* src/*.pdf src/*.png;
              do curl --silent -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/exercicis/;
              done;


