# Workflow to publish all notebooks

name: Publish Notebooks

on:
  push:
    branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir -p exercises solutions

      - name: Install dependencies
        run: sudo apt-get update && pip install jupytext
        
      - name: Add artifacts to publish to the temp folder
        run: for file in src/*md;do jupytext --to ipynb src/$file -o solutions/"${file%_solutions.ipynb}" && ./make-student-version solutions/"${file%_solutions.ipynb}" > exercises/"${file%.ipynb}";done;

      - name: Upload exercises
        uses: actions/upload-artifact@v2
        with:
          name: exercises
          path: exercises

      - name: Upload solutions
        uses: actions/upload-artifact@v2
        with:
          name: solutions
          path: solutions
