# Workflow to publish all notebooks and upload to Nextcloud

name: Publish Notebooks

on:
  push:
    branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Create a temporary artifact downloads folder
        run: mkdir -p exercises solutions

      - name: Install dependencies
        run: sudo apt-get update && pip install jupytext
        
      - name: Print debugging info
        run: pwd; ls
        
      - name: Add artifacts to publish to the temp folder
        run: for file in src/*md;do jupytext --to ipynb $file -o solutions/`basename -s .md $file`_solutions.ipynb && ./make-student-version solutions/`basename -s .md $file`_solutions.ipynb > exercises/`basename -s .md $file`.ipynb;done;

      - name: Upload exercises
        uses: actions/upload-artifact@v2
        with:
          name: exercises
          path: exercises

      - name: Upload solutions
        uses: actions/upload-artifact@v2
        with:
          name: solutions
          path: solutions
          
      - name: Nextcloud Artifact
        uses: trympet/nextcloud-artifacts-action@v2
        with:
          name: 'my-artifact'                                   # Name of the artifact
          path: 'exercises/*'                                  # Globbing supported
          nextcloud-url: 'mat.uab.cat/nextcloud'        # Nextcloud URL
          nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }} # Username from repository secret
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }} # Password from repository secret
