# Workflow to publish all notebooks and upload to Nextcloud

name: Publish Notebooks

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    container:
      image : sagemath/sagemath:latest
      options: --user root

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Create a temporary artifact downloads folder
        run: mkdir -p output
          
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wget python3-pip curl texlive-latex-extra
          sudo pip install jupytext nbconvert ipython ipykernel
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo dpkg -i pandoc-2.18-1-amd64.deb
          sudo apt-get install -f

        
      - name: Make notebooks
        run: |
            cd src
            for file in *.md;
              do ../process_file $file || true
              done;
            cd ..
              
      - name: Upload to Nextcloud
        run: for file in output/*.pdf output/*.ipynb src/*.pdf src/*.png src/*.jpg; do
              [ -f "$file" ] && curl --silent -X PUT -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T $file https://mat.uab.cat/nextcloud/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/EIM/exercicis/;
              done;


